import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import profile from "public/images/profile/Hotpot2.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";
import HireMe from "@/components/HireMe";
import bulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import Transition from "@/components/Transition";

export default function Home() {
	return (
		<>
			<Head>
				<title>Ugonna's Portfolio</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Transition/>
			<main className="dark:text-light lg:max-2xl:flex lg:max-2xl:!top-1 !top-14 !relative sm:max-lg:top-11 sm:max-lg:relative z-0 flex items-center text-dark w-full min-h-screen">
				<Layout className="pt-0">
					<div className="flex flex-col md:flex-row items-center justify-between w-full">
						<div className="w-1/2 md:w-full">
							<Image
								src={profile}
								className="md:animate-bounce-slow
								 w-full lg:w-96 h-auto md:max-lg:hidden rounded-full mt-12 sm:mt-16"
								 priority
								 sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
							/>
						</div>
						<div className=" md:ml-8 md:max-lg:top-16 relative md:mt-0 sm:mt-16 flex flex-col items-center self ">
							<h1 className="mt-6 font-thin block w-full flex-wrap text-dark capitalize text-6xl dark:text-light ">
								Hello I'm Ugonna,
							</h1>
							<AnimatedText
								className=" justify-center mb-10"
								text=" FRONTEND ENGINEER  "
								
							/>
							<p className="my-4 text-base font-medium">
								As a skilled Frontend Engineer, I am dedicated to turning ideas
								into innovative web applications. Welcome to my portfolio as you
								explore my latest projects and work experience, showcasing my
								expertise in React.js and software development.
							</p>
							<div className="flex items-center self-start mt-2">
								<Link
									className="dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light  flex items-center justify-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
              hover:bg-light hover:text-dark border-2 border-transparent hover:border-dark"
									href="/experience"
									>
									Resume <LinkArrow className="pl-1 w-6" />
								</Link>
								<Link
									className="dark:text-light ml-4 text-lg font-medium capitalize text-dark underline"
									href="mailto:ugonnagodson512@gmail.com"
									target={"_blank"}>
									Contact
								</Link>
							</div>
						</div>
					</div>
				</Layout>

				<HireMe />
				<div className="absolute right-2 bottom-2 lg:inline-block w-24 hidden">
					<Image src={bulb} alt="Lightbulb" className="w-full h-auto" />
				</div>
			</main>
		</>
	);
}
